#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --output=install_env_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

cd /home/fshi/xft-moe
conda env create -f xft_env.yml
source activate xft
pip install torch==2.1.1 torchvision==0.16.1 --index-url https://download.pytorch.org/whl/cu118
pip install flash-attn==2.3.1.post1  --no-build-isolation
